### ISSUE TITLE
saving filterbank file

### ISSUE THREAD

**Issue by mserylak** [ewanbarr/sigpyproc#3]
Hi Ewan,

Is there a way, after changing header parameters with e.g. file.header.fch1 = X.XX;file.header.updateHeader(), to write out such corrected file to disk?

Best regards,
Maciej

**Comment by ewanbarr** [comment]
Something like this should do it:

out_file = file.header.prepOutfile("my_new_file.fil", back_compatible=True)
for nsamps,ii,data in self.readPlan(512):
    out_file.cwrite(data)
out_file.close()

There is also a function in sigpyproc.Utils called:
editInplace(inst,key,value)

Beware that for some header changes this can be dangerous, so test it on
copy first. This function will correct the header without writing a new
file, i.e. it does it in-place. In your case you would use it like:

editInplace(file,"fch1",<new fch1 value>)

Cheers,
Ewan

**Comment by mserylak** [comment]
Forgot to close this ;) Thanks!
